# Generated by Django 3.2.12 on 2025-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20250413_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'category')},
        ),
    ]
